data:
  processed_dir: 'data/processed'
  train_csv: 'train.csv'
  val_csv: 'val.csv'
  test_csv: 'test.csv'
  mappings: 'attribute_mappings.json'
  image_dir: 'data/raw/Images' 

model:
  vision_model_name: 'google/vit-base-patch16-224-in21k'
  # ANNOTATION: This is the key parameter that configures the SiloedModel for a specific job.
  task: 'price'

training:
  epochs: 10
  batch_size: 16
  learning_rate: 1e-4
  device: 'cuda'

output_dir: 'results/'
experiment_name: 'exp1_1_siloed_price'
