# --- START OF FILE configs/exp1_1_siloed_attributes.yaml ---
data:
  processed_dir: 'data/processed'
  train_csv: 'train.csv'
  val_csv: 'val.csv'
  mappings: 'attribute_mappings.json'
  image_dir: 'data/raw/Images' 

model:
  vision_model_name: 'google/vit-base-patch16-224-in21k'
  # ANNOTATION: Setting the task to 'attributes' will build the attribute classification model.
  task: 'attributes'

training:
  epochs: 10
  batch_size: 16
  learning_rate: 1e-4
  device: 'cuda'

output_dir: 'results/'
experiment_name: 'exp1_1_siloed_attributes'
# --- END OF FILE configs/exp1_1_siloed_attributes.yaml ---