data:
  processed_dir: 'data/processed'
  train_csv: 'train.csv'
  val_csv: 'val.csv'
  mappings: 'attribute_mappings.json'
  image_dir: 'data/raw/Images' 

model:
  vision_model_name: 'google/vit-base-patch16-224-in21k'
  text_model_name: 'gpt2'

training:
  epochs: 10
  batch_size: 16
  learning_rate: 1e-4
  device: 'cuda'
  log_image_freq: 5

wandb:
  project: 'multimodal-product-lister'

output_dir: 'results/'
experiment_name: 'exp2_1_direct_vlm'